apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv-tests
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: "/home/michael/volumes"
    path: "/root/volumes"




    