apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc-tests
  labels:
    type: local
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: postgres-pv-tests
  storageClassName: standard
  # storageClassName: do-block-storage
